### ISSUE TITLE
Wrong commandline is generated for atleast Katello-3.X

### ISSUE THREAD

**Issue by JvdW** [theforeman/foreman_setup#25]
Installed this plugin under Katello-3.X and it generates the wrong commandline in  foreman_setup/app/views/foreman_setup/provisioners/_step3.html.erb
It checks for Katello vs Foreman but Katello switched to foreman-installer instead of katello-installer since version 3.0 or higher (might even be since 2.4, I'm not sure)

**Comment by domcleal** [comment]
Fixed in #26.
