### ISSUE TITLE
wrong arguments used in step 3 "Foreman Installer"

### ISSUE THREAD

**Issue by metalcated** [theforeman/foreman_setup#38]
Wrong arguments: 
--foreman-proxy-parent-fqdn=
--foreman-proxy-foreman-oauth-key
--foreman-proxy-foreman-oauth-secret

Correct Arguments:
--foreman-proxy-content-parent-fqdn
--foreman-proxy-oauth-consumer-key
--foreman-proxy-oauth-consumer-secret

RPM version: tfm-rubygem-foreman_setup-7.0.0-1.fm1_24.el7.noarch

Thanks

**Comment by lzap** [comment]
Thanks a5fc6a9
